services:
  - type: web
    name: supercube-backend-service
    runtime: image
    plan: free
    numInstances: 1
    image:
      url: php:8.2-apache
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: supercube-db
          property: connectionString
      - key: APACHE_DOCUMENT_ROOT
        value: /var/www/html

databases:
  - name: supercube-db
    plan: free
